# See also dependencies in ../.tool-versions
[tools]
node = "22.14.0"
python = "3.10.2"

# For linting documentation
markdownlint-cli2 = "0.19.0"
lychee = "0.21.0"
vale = "3.13.0"

[env]
'_'.path = ["{{config_root}}/node_modules/.bin"]
